# Generated by Django 2.2.3 on 2020-05-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='小区名称')),
                ('biz', models.CharField(max_length=64, verbose_name='开发商')),
                ('price', models.IntegerField(verbose_name='售价')),
                ('like', models.CharField(max_length=64, verbose_name='户型')),
                ('station', models.CharField(max_length=64, verbose_name='位置')),
                ('x', models.FloatField(verbose_name='地图坐标x')),
                ('y', models.FloatField(verbose_name='地图坐标y')),
                ('pic', models.ImageField(upload_to='media', verbose_name='图片')),
                ('state', models.BooleanField(default=True, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号码')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=32, verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.House', verbose_name='记录')),
            ],
            options={
                'verbose_name': '修改',
                'verbose_name_plural': '修改',
            },
        ),
    ]
