# Generated by Django 2.2.3 on 2020-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200502_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='content',
            field=models.TextField(default='hhh', verbose_name='修改建议'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='like',
            field=models.CharField(choices=[('一居室', '一居室'), ('二居室', '二居室'), ('三居室', '三居室'), ('更多', '更多')], max_length=64, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='图片'),
        ),
    ]
