# Generated by Django 2.2 on 2021-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210131_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='节点名称')),
                ('state', models.CharField(max_length=64, verbose_name='节点状态')),
                ('sum', models.IntegerField(verbose_name='当前样本数')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Node',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DateField(auto_now_add=True, verbose_name='任务编号')),
                ('one', models.IntegerField(verbose_name='身体条件得分')),
                ('two', models.IntegerField(verbose_name='家庭条件得分')),
                ('three', models.IntegerField(verbose_name='性格状况得分')),
                ('four', models.IntegerField(verbose_name='心理状况得分')),
                ('five', models.IntegerField(verbose_name='工作状况得分')),
                ('score', models.IntegerField(verbose_name='总得分')),
                ('state', models.CharField(choices=[('极低', '极低'), ('偏低', '偏低'), ('正常', '正常'), ('良好', '良好'), ('优秀', '优秀')], max_length=64, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Work',
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='house',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
