# Generated by Django 2.2 on 2021-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210304_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数据量'),
        ),
    ]
