# Generated by Django 2.2 on 2021-03-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_line_message_news_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='station',
            name='long',
        ),
    ]
