# Generated by Django 2.2 on 2021-03-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210315_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Station', verbose_name='景点'),
        ),
    ]
