# Generated by Django 2.2 on 2021-03-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_message_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='处置机构')),
                ('password', models.CharField(max_length=64, verbose_name='处置机构密码')),
                ('name', models.CharField(max_length=64, verbose_name='处置机构名称')),
                ('content', models.CharField(max_length=64, verbose_name='处置机构介绍')),
                ('isLogin', models.BooleanField(default=False, verbose_name='处置机构审核')),
                ('x', models.FloatField(verbose_name='平面X坐标')),
                ('y', models.FloatField(verbose_name='平面Y坐标')),
            ],
            options={
                'verbose_name': '处置机构',
                'verbose_name_plural': '处置机构',
            },
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='医疗订单编号')),
                ('kg', models.FloatField(verbose_name='重量')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('medicalDate', models.DateField(auto_now_add=True, verbose_name='医废订单创建时间')),
                ('transportDate', models.DateField(verbose_name='运输接受时间')),
                ('arvieDate', models.DateField(verbose_name='运输到达时间')),
                ('completeDate', models.DateField(verbose_name='处理完成订单')),
                ('kind', models.CharField(choices=[('感染性', '感染性'), ('病理性', '病理性'), ('损伤性', '损伤性'), ('药物性', '药物性'), ('化学性', '化学性')], max_length=64, verbose_name='医疗废物类别')),
                ('stateKind', models.CharField(choices=[('待接受', '待接收'), ('待运输', '待运输'), ('运输中', '运输中'), ('已到达', '已到达'), ('处置完成', '处置完成')], max_length=64, verbose_name='目前状态')),
                ('endState', models.CharField(choices=[('填埋', '填埋'), ('焚烧', '焚烧'), ('原料加工处理', '原料加工处理')], max_length=64, verbose_name='处置状态')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company', verbose_name='处置机构')),
            ],
            options={
                'verbose_name': '医废订单',
                'verbose_name_plural': '医废订单',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='医废名称')),
                ('content', models.TextField(verbose_name='医废分类标准')),
            ],
            options={
                'verbose_name': '医疗废物',
                'verbose_name_plural': '医疗废物',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='操作对象')),
                ('kind', models.CharField(max_length=64, verbose_name='操作记录')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='医疗机构')),
                ('password', models.CharField(max_length=64, verbose_name='医疗机构密码')),
                ('name', models.CharField(max_length=64, verbose_name='医疗机构名称')),
                ('content', models.CharField(max_length=64, verbose_name='医疗机构介绍')),
                ('isLogin', models.BooleanField(default=False, verbose_name='医疗机构登录权限')),
                ('x', models.FloatField(verbose_name='平面X坐标')),
                ('y', models.FloatField(verbose_name='平面Y坐标')),
            ],
            options={
                'verbose_name': '医疗机构',
                'verbose_name_plural': '医疗机构',
            },
        ),
        migrations.RemoveField(
            model_name='line',
            name='station',
        ),
        migrations.RemoveField(
            model_name='line',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='station',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='station',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='isLogin',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='935913424@qq.com', max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('医疗机构工作人员', '医疗机构工作人员'), ('运输人员', '运输人员'), ('处置人员', '处置人员')], default='打工人', max_length=64, verbose_name='用户身份'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='普通用户登录权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=64, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='普通用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='普通用户账号'),
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='indent',
            name='completeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completeuser', to='user.User', verbose_name='处置人员'),
        ),
        migrations.AddField(
            model_name='indent',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Medical', verbose_name='医疗机构'),
        ),
        migrations.AddField(
            model_name='indent',
            name='medicalUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaluser', to='user.User', verbose_name='医疗机构工作人员'),
        ),
        migrations.AddField(
            model_name='indent',
            name='transportUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportuser', to='user.User', verbose_name='运输人员'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company', verbose_name='处置机构'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Medical', verbose_name='医疗机构'),
        ),
    ]
