# Generated by Django 2.2 on 2021-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210317_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='islogin',
        ),
        migrations.AddField(
            model_name='user',
            name='isLogin',
            field=models.CharField(choices=[('已审核', '已审核'), ('未审核', '未审核')], default='未审核', max_length=64, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='企业资格证书'),
        ),
        migrations.AlterField(
            model_name='company',
            name='isLogin',
            field=models.CharField(choices=[('已审核', '已审核'), ('未审核', '未审核')], default='未审核', max_length=64, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='企业资格证书'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='isLogin',
            field=models.CharField(choices=[('已审核', '已审核'), ('未审核', '未审核')], default='未审核', max_length=64, verbose_name='审核状态'),
        ),
    ]
