# Generated by Django 2.2 on 2021-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210317_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='平面X坐标'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='平面Y坐标'),
        ),
    ]
