# Generated by Django 2.2 on 2021-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210317_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isWork',
            field=models.CharField(choices=[('已入职', '已入职'), ('待入职', '待入职')], default='待入职', max_length=64, verbose_name='是否工作'),
        ),
    ]
