# Generated by Django 2.2 on 2021-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_iswork'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='content',
            field=models.TextField(default='sadas', verbose_name='病理描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indent',
            name='endState',
            field=models.CharField(blank=True, choices=[('填埋', '填埋'), ('焚烧', '焚烧'), ('原料加工处理', '原料加工处理')], max_length=64, null=True, verbose_name='处置状态'),
        ),
    ]
