# Generated by Django 2.2 on 2021-03-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210318_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='arvieDate',
            field=models.DateField(null=True, verbose_name='运输到达时间'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='completeDate',
            field=models.DateField(null=True, verbose_name='处理完成订单'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='transportDate',
            field=models.DateField(null=True, verbose_name='运输接受时间'),
        ),
    ]
