# Generated by Django 2.2 on 2021-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210318_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='意见反馈内容')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '意见反馈内容',
                'verbose_name_plural': '意见反馈内容',
            },
        ),
        migrations.AlterField(
            model_name='indent',
            name='arvieDate',
            field=models.DateField(blank=True, null=True, verbose_name='运输到达时间'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='completeDate',
            field=models.DateField(blank=True, null=True, verbose_name='处理完成订单'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='stateKind',
            field=models.CharField(choices=[('待接受', '待接受'), ('待运输', '待运输'), ('运输中', '运输中'), ('已到达', '已到达'), ('处置完成', '处置完成')], max_length=64, verbose_name='目前状态'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='transportDate',
            field=models.DateField(blank=True, null=True, verbose_name='运输接受时间'),
        ),
    ]
