# Generated by Django 2.2 on 2021-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210319_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '数据可视化',
            },
        ),
    ]
