# Generated by Django 2.2 on 2021-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_fenxi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fenxi',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='completeUser',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='medicalUser',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='transportUser',
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '普通用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isWork',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=32, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isLogin',
            field=models.BooleanField(default=False, verbose_name='登录状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='账号'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Indent',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
    ]
