# Generated by Django 2.2 on 2021-03-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210324_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '日期',
                'verbose_name_plural': '日期',
            },
        ),
        migrations.CreateModel(
            name='ShortNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('pub_time', models.DateTimeField(verbose_name='创建时间')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Date', verbose_name='日期')),
            ],
            options={
                'verbose_name': '短新闻',
                'verbose_name_plural': '短新闻',
            },
        ),
    ]
