# Generated by Django 2.2 on 2021-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_date_shortnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortnews',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AddField(
            model_name='shortnews',
            name='kind',
            field=models.CharField(choices=[('长新闻', '长新闻'), ('短新闻', '短新闻'), ('新闻联播', '新闻联播')], default='新闻', max_length=64, verbose_name='新闻种类'),
            preserve_default=False,
        ),
    ]
