# Generated by Django 2.2 on 2021-03-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210324_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnews',
            name='title',
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='kind',
            field=models.CharField(max_length=64, verbose_name='新闻种类'),
        ),
    ]
